"""
WHAT  - a minimal LLMProvider interface with one concrete implementation
        (Gemini), plus shared retry-on-invalid-structured-output helpers.
        Every other file calls get_llm_provider() instead of importing
        google.genai directly, so swapping providers later is a config
        change, not a rewrite.

WHY   - required by the original architecture: "LLM service/interface ->
        provider implementation" so the provider is replaceable.

HOW   - app/tools/*.py call generate_structured_with_retry(provider, prompt, schema).
        The learning-plan tool uses the raw-schema helper because its nested
        schema cannot safely be auto-derived by the pinned google-genai SDK.
"""

import json
import logging
from typing import TypeVar

from fastapi import HTTPException, status
from pydantic import BaseModel, ValidationError
from google import genai
from google.genai import types

from app.core.config import settings

logger = logging.getLogger("llm_provider")

T = TypeVar("T", bound=BaseModel)


class LLMProvider:
    def generate_structured(self, prompt: str, schema: type[T]) -> T:
        raise NotImplementedError


class GeminiProvider(LLMProvider):
    def __init__(self):
        self._client = genai.Client(api_key=settings.gemini_api_key)

    def generate_structured(self, prompt: str, schema: type[T]) -> T:
        # NOTE: gemini-2.5-flash was retired for new users; gemini-3.5-flash
        # is the current working model - do not revert.
        response = self._client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=schema,
            ),
        )
        return schema.model_validate_json(response.text)

    def generate_with_raw_schema(
        self,
        prompt: str,
        raw_schema: dict,
        parse_model: type[T],
    ) -> T:
        """
        Same as generate_structured, but the schema sent to Gemini is given
        explicitly instead of being auto-derived from parse_model.

        Needed specifically for schemas containing nested objects because
        the pinned google-genai SDK does not safely handle the $ref/$defs
        generated by Pydantic for this schema.
        """
        response = self._client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=raw_schema,
            ),
        )
        return parse_model.model_validate_json(response.text)


def get_llm_provider() -> LLMProvider:
    """
    Reads LLM_PROVIDER from settings and returns the matching implementation.
    Only "gemini" is implemented right now; a GroqProvider can be added here
    later (LLM_PROVIDER=groq) without touching any tool.
    """
    if settings.llm_provider == "gemini":
        return GeminiProvider()

    raise NotImplementedError(
        f"LLM provider '{settings.llm_provider}' is not implemented yet."
    )


def generate_structured_with_retry(
    provider: LLMProvider,
    prompt: str,
    schema: type[T],
) -> T:
    """
    Calls provider.generate_structured(), retrying once if the model's output
    does not validate against the requested Pydantic schema.

    Network/auth/quota/schema errors from the provider itself are NOT retried.
    They fail fast with a 502 and are logged server-side.
    """
    last_error = None

    for _ in range(2):
        try:
            return provider.generate_structured(prompt, schema)

        except (ValidationError, ValueError, json.JSONDecodeError) as exc:
            last_error = exc
            prompt += (
                "\n\nReturn ONLY valid JSON matching the exact schema "
                "requested. No extra text."
            )

        except Exception as exc:
            logger.exception(
                "LLM call failed for schema %s",
                schema.__name__,
            )
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="The AI service is unavailable right now. Please try again.",
            ) from exc

    logger.warning(
        "LLM returned invalid structure for schema %s after retry: %s",
        schema.__name__,
        last_error,
    )

    raise HTTPException(
        status_code=status.HTTP_502_BAD_GATEWAY,
        detail="The AI service returned an unexpected response. Please try again.",
    ) from last_error


def generate_with_raw_schema_and_retry(
    provider: GeminiProvider,
    prompt: str,
    raw_schema: dict,
    parse_model: type[T],
) -> T:
    """
    Calls Gemini using an explicitly supplied raw JSON schema and retries once
    if the returned JSON does not validate against parse_model.

    This is used by the learning-plan tool because its nested Pydantic schema
    generates $ref/$defs, which the pinned google-genai SDK does not handle
    correctly on the normal response_schema path.
    """
    last_error = None

    for _ in range(2):
        try:
            return provider.generate_with_raw_schema(
                prompt,
                raw_schema,
                parse_model,
            )

        except (ValidationError, ValueError, json.JSONDecodeError) as exc:
            last_error = exc
            prompt += (
                "\n\nReturn ONLY valid JSON matching the exact schema "
                "requested. No extra text."
            )

        except Exception as exc:
            logger.exception(
                "LLM call failed for schema %s (raw schema path)",
                parse_model.__name__,
            )
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="The AI service is unavailable right now. Please try again.",
            ) from exc

    logger.warning(
        "LLM returned invalid structure for schema %s after retry: %s",
        parse_model.__name__,
        last_error,
    )

    raise HTTPException(
        status_code=status.HTTP_502_BAD_GATEWAY,
        detail="The AI service returned an unexpected response. Please try again.",
    ) from last_error


def _learning_plan_gemini_schema() -> dict:
    """
    Hand-built JSON schema for the learning plan.

    We deliberately return a plain Python dictionary instead of
    types.Schema. google-genai==0.5.0 has a schema-conversion path
    specifically for dictionaries, while constructing nested types.Schema
    objects causes an internal transformer error.

    The schema is fully inlined to avoid the $ref/$defs problem produced
    by Pydantic's nested model schema.
    """
    return {
        "type": "OBJECT",
        "properties": {
            "items": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "skill": {
                            "type": "STRING"
                        },
                        "priority": {
                            "type": "STRING"
                        },
                        "recommended_area": {
                            "type": "STRING"
                        },
                        "difficulty": {
                            "type": "STRING"
                        },
                        "order": {
                            "type": "INTEGER"
                        },
                        "term": {
                            "type": "STRING"
                        },
                        "resources": {
                            "type": "ARRAY",
                            "items": {
                                "type": "STRING"
                            }
                        }
                    },
                    "required": [
                        "skill",
                        "priority",
                        "recommended_area",
                        "difficulty",
                        "order",
                        "term",
                        "resources"
                    ]
                }
            }
        },
        "required": [
            "items"
        ]
    }